language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip3 install -r requirements.txt"
  - "pip3 install -r requirements.dev.txt"
# command to run tests
script: 
  - "pep8 ."
  - "touch ./instance/config.py"
  - "python3 test.py"
